---

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600

# The valid ingress certificate issuer values
cert_issuer_set:
- staging
- production

# The namespace of the deployment,
# our 'infrastructure'. We anticipate
# deploying postgres, the AWX server and Keycloak here.
infra_namespace: im-infra
infra_namespace_service_account: im-infra
# The node 'purpose' for workload deployments.
# The database, AWX server and keycloak deployments will try to deploy
# workloads to nodes that contain the label "purpose={{ node_purpose }}".
infra_node_purpose: application

# Postgres --------------------------------------------------------------------

# The infrastructure database version.
# For AWX the minimum version is 9.6+
pg_version: '12.1-alpine'

# Postgres superuser details
pg_user: governor
pg_user_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters,digits') }}"
pg_database: governor

# CPU and Memory requests and limits
pg_cpu_request: 250m
pg_cpu_limit: 1000m
pg_mem_request: 100Mi
pg_mem_limit: 500Mi

# Backup ----------------------------------------------------------------------

# Backups run as a CronJob.
# Set the schedule (and the number of hourly backups to keep) here.
pg_bu_hourly_schedule: '7 * * * *'
pg_bu_hourly_history: 24
# The backup container image tag.
pg_bu_image_tag: stable
# The image pull policy for the backup container image.
pg_bu_imagepullpolicy: IfNotPresent

# AWX -------------------------------------------------------------------------

# The AWX server version.
# A tag for the AWX github repo (See https://github.com/ansible/awx)
ax_version: '9.1.0'

# The directory (on the client) where the AWX repo
# (including the built-in installation playbook)
# will be cloned. AWX will be adjusted and installed from here.
ax_clone_dir: /tmp

# The AWX platform.
# Typically 'kubernetes' or 'openshift' where supported.
# A deploy-{{ ax-platform }}-awx-{{ ax_version }}.yml file must exist
ax_platform: kubernetes
# The AWX task_cpu_request. This controls the CPU requests
# for all the containers in the AWX Pod. This (for 9.1.0) is 1500 (1.5 cores).
# Reduce this for compact deployments or minikube experiments.
# The value (expected to be a number) is used if not 'default'.
ax_task_cpu_request: default

ax_user: awx
ax_user_password: "{{ lookup('password', '/dev/null length=10 chars=ascii_letters,digits') }}"
ax_database: awx

# Keycloak --------------------------------------------------------------------

kc_version: '8.0.1'

kc_user: keycloak
kc_user_password: "{{ lookup('password', '/dev/null length=10 chars=ascii_letters') }}"
kc_database: keycloak

# CPU and Memory requests and limits
kc_cpu_request: 250m
kc_cpu_limit: 250m
kc_mem_request: 1024Mi
kc_mem_limit: 1024Mi
