---

# Check we're able to continue...

- name: Pre-flight checks
  assert:
    that:
    - aws_access_key|length > 0
    - awx_secret_key|length > 0

# Go...

- include_tasks: deploy.yml
  when: efs_state|string == 'present'
- include_tasks: undeploy.yml
  when: efs_state|string == 'absent'
