---

- name: Pre-flight checks
  assert:
    that:
    - nfs_server_address|string|length > 0
    - nfs_server_address|string != 'SetMe'
    - nfs_dynamic_export|string|length > 0
    - nfs_dynamic_export|string != 'SetMe'

- name: Display key NFS facts
  debug:
    msg: server_address={{ nfs_server_address }} dynamic_export={{ nfs_dynamic_export }}

# Install an NFS provisioner and create a StorageClass

- name: Deploy namespace
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - namespace

- name: Create DockerHub image pull secret
  k8s:
    definition: "{{ lookup('template', 'secret-dh-imagepull.yaml.j2') }}"
    wait: yes
  vars:
    pull_namespace: "{{ nfs_namespace }}"
    pull_secret: "{{ infra_dockerhub_pullsecret }}"
  when: infra_dockerhub_pullsecret|string|length > 0

- name: Deploy
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - serviceaccount
  - clusterrole
  - clusterrolebinding
  - role
  - rolebinding
  - deployment
  - storageclass
