---

- name: Pre-flight checks
  assert:
    that:
    - nfs_server_address|string|length > 0
    - nfs_server_address|string != 'SetMe'

- name: Display key NFS facts
  debug:
    msg: nfs_server_address={{ nfs_server_address }} nfs_path={{ nfs_path }}

# Install an NFS provisioner and create a StorageClass

- name: Deploy
  k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - namespace
  - serviceaccount
  - clusterrole
  - clusterrolebinding
  - role
  - rolebinding
  - deployment
  - storageclass
