---

# Deleting the namespace deletes a lot of stuff for us...

- name: Deleting namespace '{{ nfs_namespace }}'
  k8s:
    state: absent
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes
