---

# Deleting the namespace deletes a lot of stuff for us...

- name: Deleting namespace '{{ nfs_namespace }}'
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes

- name: Delete NFS objects
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - storageclass
  - clusterrolebinding
  - clusterrole
