---

# Check we're able to continue...

- name: Pre-flight checks
  ansible.builtin.assert:
    that:
    - aws_access_key|string|length > 0
    - awx_secret_key|string|length > 0
    - efs_backing_volume_name|string|length > 0

# Go...

- ansible.builtin.include_tasks: deploy.yaml
  when: efs_state|string == 'present'
- ansible.builtin.include_tasks: undeploy.yaml
  when: efs_state|string == 'absent'
