---

roles:
- src: informaticsmatters.cert_manager
  version: 0.12.0
- src: geerlingguy.nfs
  version: 1.5.0
- src: geerlingguy.docker
  version: 2.7.0
- src: geerlingguy.ntp
  version: 2.0.1
- src: geerlingguy.certbot
  version: 3.1.0

collections:
- name: awx.awx
  version: 13.0.0
