---

# Configure the Rancher server.
# Installing Docker, CertBot and then Rancher.
#
# You should set the environment variable CERTBOT_EMAIL

- hosts: rancher[0]
  vars:
    pip_install_packages:
    - name: docker
  roles:
  - role: geerlingguy.pip
    become: yes
  - role: geerlingguy.docker
    become: yes
  - role: rancher