---

# Applies the recovery role.
# The database backup to recover should be
# passed-in via the 'recovery_from_backup' variable.

- hosts: control
  roles:
  - role: infrastructure-recovery
    vars:
      recovery_from_backup: none
