---

- hosts: infra_server
  roles:
  - role: ingress-controller
    when: ic_state|string == 'present'
  - role: informaticsmatters.cert_manager
    when: cm_state|string == 'present'
  - role: provisioner-cinder
    when: cinder_state|string == 'present'
  - role: provisioner-efs
    when: efs_state|string == 'present'
#  - role: provisioner-nfs
#    when: nfs_state|string == 'present'
  - role: infrastructure
