---

# Configure the RKE cluster - installing
# Docker in preparation for RKE installation.

- hosts: rke
  vars:
    pip_install_packages:
    - name: docker
  roles:
  - role: geerlingguy.pip
    become: yes
  - role: geerlingguy.docker
    become: yes
  - role: rke
