---

- hosts: control
  roles:
  - role: core
    when: core_state|string == 'present'
  - role: informaticsmatters.cert_manager
    when: cm_state|string == 'present'
  - role: provisioner-cinder
    when: cinder_state|string == 'present'
  - role: provisioner-efs
    when: efs_state|string == 'present'
  - role: provisioner-nfs
    when: nfs_state|string == 'present'
  - role: infrastructure
    when: infra_state|string == 'present'
