---

# Namespace for the deployment
nfs_namespace: im-nfs-client-provisioner

# A symbolic name for the provisioner deployment,
# used to direct the storage-class to the provisioner Pod.
nfs_provisioner_name: informaticsmatters.com/nfs
# The name used for the storage class that will be created.
nfs_storage_class_name: nfs

# The container image tag and registry.
# One valid for quay.io/repository/external_storage/nfs-client-provisioner
nfs_provisioner_tag: v3.1.0-k8s1.11
nfs_provisioner_registry: quay.io

# The node 'purpose' for workload deployments.
nfs_node_purpose: application

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600

# Provisioner Pod Requests/Limits
nfs_cpu_limit: 200m
nfs_mem_limit: 128Mi
nfs_cpu_request: 100m
nfs_mem_request: 128Mi
