---

# Namespace for the deployment
nfs_namespace: im-nfs-client-provisioner

# The name used for the storage class that will be created.
nfs_storage_class_name: nfs

# The container image tag and registry.
# One valid for quay.io/repository/external_storage/nfs-client-provisioner
nfs_provisioner_tag: v4.0.2

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600

# Provisioner Pod Requests/Limits
nfs_cpu_limit: 200m
nfs_mem_limit: 128Mi
nfs_cpu_request: 100m
nfs_mem_request: 128Mi
