---

# Add our Keycloak realm.
# The steps here are: -
#
# - Get a list of realms
# - Add the realm if it's not known

- name: Get Keycloak token
  import_tasks: get-keycloak-token.yaml
  vars:
    realm: master
    realm_user: "{{ kc_admin_fact }}"
    realm_user_password: "{{ kc_admin_password_fact }}"

- name: Set API endpoint
  set_fact:
    keycloak_endpoint: https://{{ kc_hostname }}/auth/admin/realms

- name: Get existing Realms
  uri:
    url: "{{ keycloak_endpoint }}"
    headers:
      Authorization: bearer {{ kc_token }}
  register: realms
  changed_when: False

# The above 'query' results in a 'realms' variable. A structure
# with each query represented as an element in the 'json' array.
# i.e.
#
#  "json": [{
#     "realm": "master"
#
# To simplify further processing, we'd like a nice flat list.
- name: Collect known Realms
  set_fact:
    known_realms: "{{ realms|json_query('json[*].realm')|flatten }}"

# Now, add all the realms we need...

- name: Add Realm (if it does not exist)
  uri:
    url: "{{ keycloak_endpoint }}"
    method: POST
    body: >-
      {"realm": "{{ kc_realm }}",
       "enabled": "true"}
    body_format: json
    status_code: 201
    headers:
      Authorization: bearer {{ kc_token }}
  when:
  - kc_realm not in known_realms
