---

- name: Check variables
  assert:
    that:
    - kc_manager_fact is defined
    - kc_manager_password_fact is defined
    - kc_hostname is defined
    - kc_realm is defined

- name: Set API endpoint
  set_fact:
    user_endpoint: https://{{ kc_hostname }}/auth/admin/realms/{{ kc_realm }}

- name: Add manager
  uri:
    url: "{{ user_endpoint }}/users"
    method: POST
    body: >-
      {"username": "{{ kc_manager_fact }}",
       "enabled": "true"}
    body_format: json
    status_code: 201
    headers:
      Authorization: bearer {{ kc_token }}
    return_content: yes
  register: manager_resp

# The user ID is in the returned 'location' field.
# "location": "https://sso.192.168.99.100.nip.io/auth/admin/realms/squonk/
#                users/394c1e02-0b2b-433c-9512-0bfce6aabf9d"

- name: Extract assigned user ID
  set_fact:
    kc_manager_user_id: >-
      {{ manager_resp
         |json_query('location')
         |urlsplit('path')
         |basename }}

- name: Asssert ID
  assert:
    that:
    - kc_manager_user_id is defined
    - kc_manager_user_id|length > 0

- name: Set (Reset) manager password
  uri:
    url: "{{ user_endpoint }}/users/{{ kc_manager_user_id }}/reset-password"
    method: PUT
    body: >-
      {"type": "password",
       "temporary": "false",
       "value": "{{ kc_manager_password_fact }}"}
    body_format: json
    status_code: 204
    headers:
      Authorization: bearer {{ kc_token }}
