---

# Alters a database user's password.
# Key, required, variables are: -
#
# - db_user
# - db_user_namespace <- A namespace (which must exist)
# - db_user_password  <- Optional ... randomly generated if not defined

- name: Pre-flight check
  assert:
    that:
    - db_user is defined
    - db_user|string|length > 0
    - db_user != 'SetMe'
    - db_user_namespace is defined
    - db_user_namespace|string|length > 0
    - db_user_namespace != 'SetMe'

- name: Get user namespace
  k8s_facts:
    kind: Namespace
    name: "{{ db_user_namespace }}"
  register: ns_result

- name: Assert user namespace
  assert:
    that: ns_result.resources|length == 1
    fail_msg: User namespace does not exist

- name: Get secrets (from {{ db_user_namespace }} namepsace)
  k8s_facts:
    kind: Secret
    name: database-secrets
    namespace: "{{ db_user_namespace }}"
  register: secret_result

- name: Assert secrets exist
  assert:
    that: secret_result.resources|length == 1
    fail_msg: Database secrets do not exist in the user's namespace

# Looks like we're ready to go...

- name: Remove any existing alter Job
  k8s:
    state: absent
    definition: "{{ lookup('template', 'job-alter-user-password.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"

- name: Launch new alter Job
  k8s:
    definition: "{{ lookup('template', 'job-alter-user-password.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"

- name: Wait for alter completion
  k8s_facts:
    kind: Job
    namespace: "{{ infra_namespace }}"
    name: alter-user-password
  register: result
  until: result.resources[0].status.completionTime is defined
  delay: 4
  retries: "{{ (wait_timeout|int / 4)|int }}"

- name: Assert delete success
  assert:
    that:
    - result.resources[0].status.succeeded is defined
    - result.resources[0].status.succeeded == 1

# Deposit new secrets into the user's namespace...

- name: Get database name (from existing secrets)
  set_fact:
    db: "{{ secret_result.resources[0].data.database_name|b64decode }}"

- name: Write new database secrets (to {{ db_user_namespace }} namepsace)
  k8s:
    definition: "{{ lookup('template', 'secret-postgres-user-db.yaml.j2') }}"
    wait: yes
