---

# Creates a database for the user.
# Key, required, variables are: -
#
# - db
# - db_user_namespace <- A namespace (which must exist)
# - db_user           <- Optional ... randomly generated if not defined
# - db_user_password  <- Optional ... randomly generated if not defined
#
# As a result of successfully adding a database (and user)
# a Secret is deposited into the user's namespace.
# With the secret present another database (for the same namespace)
# cannot be created. It is up to the user to delete this secret
# after they've deleted the database.

- name: Pre-flight check
  assert:
    that:
    - db is defined
    - db|string|length > 0
    - db_user_namespace is defined
    - db_user_namespace|string|length > 0

- name: Get user namespace
  k8s_info:
    kind: Namespace
    name: "{{ db_user_namespace }}"
  register: ns_result

- name: Assert user namespace
  assert:
    that: ns_result.resources|length == 1
    fail_msg: User namespace does not exist

- name: Get secrets (from {{ db_user_namespace }} namepsace)
  k8s_info:
    kind: Secret
    name: database-secrets
    namespace: "{{ db_user_namespace }}"
  register: secret_result

- name: Assert secrets do not exist
  assert:
    that: secret_result.resources|length == 0
    fail_msg: Database secrets already exist im the user's namespace

# Looks like we're ready to go...

- name: Remove any existing create Job
  k8s:
    state: absent
    definition: "{{ lookup('template', 'job-create-user-db.yml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"

- name: Launch new create Job
  k8s:
    definition: "{{ lookup('template', 'job-create-user-db.yml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"

- name: Wait for create completion
  k8s_info:
    kind: Job
    namespace: "{{ infra_namespace }}"
    name: create-user-db
  register: result
  until: result.resources[0].status.completionTime is defined
  delay: 4
  retries: "{{ (wait_timeout|int / 4)|int }}"

- name: Assert create success
  assert:
    that:
    - result.resources[0].status.succeeded is defined
    - result.resources[0].status.succeeded == 1

# Deposit secrets (describe the DB and password)
# into the user's namespace...

- name: Write database secrets (to {{ db_user_namespace }} namepsace)
  k8s:
    definition: "{{ lookup('template', 'secrets-postgres-user-db.yml.j2') }}"
    wait: yes
