---

# Deletes a database and the database user.
# Key, required, variables are: -
#
# - db
# - db_user           <- Optional ... randomly generated if not defined

- name: Pre-flight check
  assert:
    that:
    - db is defined
    - db|string|length > 0
    - db_user is defined
    - db_user|string|length > 0

# Looks like we're ready to go...

- name: Remove any existing delete Job
  k8s:
    state: absent
    definition: "{{ lookup('template', 'job-delete-user-db.yml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"

- name: Launch new delete Job
  k8s:
    definition: "{{ lookup('template', 'job-delete-user-db.yml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"

- name: Wait for delete completion
  k8s_info:
    kind: Job
    namespace: "{{ infra_namespace }}"
    name: delete-user-db
  register: result
  until: result.resources[0].status.completionTime is defined
  delay: 4
  retries: "{{ (wait_timeout|int / 4)|int }}"

- name: Assert delete success
  assert:
    that:
    - result.resources[0].status.succeeded is defined
    - result.resources[0].status.succeeded == 1
