---

# A general play that can operate outside of the main deployment.
# It gets the Keycloak admin user and password (from the well-known secrets)
# and then gets an API token from the server.
#
# This play expects the following: -
#
# - The realm variable to be set (i.e. 'master' or some such)
# - a Valid realm_user and realm_user_password (for the realm)
# - The kc_hostname variable to be set (i.e. 'example.com')
# - Keycloak Secrets to exist in the infrastructure namespace
#
# In return, this play sets three facts: -
#
# - kc_token

- name: Display token variables
  debug:
    msg: hostname={{ kc_hostname }} realm={{ realm }} user={{ realm_user }} password={{ realm_user_password }}

- name: Get Keycloak API token ({{ realm }} realm)
  uri:
    url: https://{{ kc_hostname }}/auth/realms/{{ realm }}/protocol/openid-connect/token
    method: POST
    body: "{{ credentials }}&grant_type=password&client_id=admin-cli"
    headers:
      Content-Type: application/x-www-form-urlencoded
  register: token_result
  vars:
    credentials: username={{ realm_user }}&password={{ realm_user_password }}
  changed_when: False

- name: Set Keycloak API token fact
  set_fact:
    kc_token: "{{ token_result.json.access_token }}"
