---

# A general play that can operate outside of the main deployment.
#
# This play expects the following: -
#
# - realm to be set (i.e. 'master' or some such)
# - realm_user and realm_user_password (for the realm)
# - kc_hostname to be set (i.e. 'example.com')
#
# In return, this play sets the fact: -
#
# - kc_token
#
# As we're used soon after the Keycloak Route/Ingress is created
# we need to re-attempt extraction of the Keycloak token a few times
# at least until the route's certificate has been generated.

- name: Get Keycloak API token ({{ realm }} realm)
  uri:
    url: https://{{ kc_hostname }}/auth/realms/{{ realm }}/protocol/openid-connect/token
    method: POST
    body: "{{ credentials }}&grant_type=password&client_id=admin-cli"
    headers:
      Content-Type: application/x-www-form-urlencoded
  register: token_result
  vars:
    credentials: username={{ realm_user }}&password={{ realm_user_password }}
  until: >-
    token_result.json is defined
    and token_result.json.access_token is defined
  delay: 4
  retries: "{{ (kc_token_timeout|int / 4)|int }}"
  changed_when: False

- name: Set Keycloak API token fact
  set_fact:
    kc_token: "{{ token_result.json.access_token }}"
