---

# Basic pre-playbook prerequisites.
# We need the openshift/kubernetes module amongst other things...

- name: Install prerequisite Python modules
  pip:
    name:
    - openshift==0.10.0
    extra_args: --user

# Check we're able to continue...

- name: Pre-flight checks
  assert:
    that:
    - aws_access_key|length > 0
    - awx_secret_key|length > 0

# Go...

- include_tasks: deploy.yml
  when: infra_state|string == 'present'
- include_tasks: undeploy.yml
  when: infra_state|string == 'absent'