---

# Common playbook preparation.

# Expose ansible version
- name: Display Ansible version
  ansible.builtin.debug:
    var: ansible_version.full

# Kubernetes credentials ------------------------------------------------------

# We don't use the Kubernetes credentials directly,
# but we load them into variables here from their
# expected environment variables so that we can assert they've been set.
#
# If we're using OpenShift credentials these environment variables
# will not be set and we will therefore rely on them being set
# from the 'login.yaml' play.

- name: Set initial authentication facts
  ansible.builtin.set_fact:
    k8s_kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
    k8s_auth_host: "{{ lookup('env', 'K8S_AUTH_HOST') }}"
    k8s_auth_api_key: "{{ lookup('env', 'K8S_AUTH_API_KEY') }}"
