---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: im-main
  region: eu-central-1

# cluster AZs must be set explicitly for single AZ nodegroup example to work
# See https://github.com/weaveworks/eksctl/blob/master/examples/05-advanced-nodegroups.yaml
availabilityZones:
- eu-central-1a
- eu-central-1b
- eu-central-1c

# By design, node groups are immutable.
#            -------------------------
# This means that if you need to change something (other than scaling)
# like the AMI or the instance type of a node group, you would need to
# create a new nodegroup with the desired changes, move the load and
# delete the old one.
#
# Our "Pod scheduling and node label policy"
# for a discussion of node labels and usage guidelines.
# See https://app.clubhouse.io/informaticsmatters/story/1312/pod-scheduling-and-node-label-policy
#
# Once created and in use - they cannot be changed.

# ----------------------
# Un-managed Node Groups
# ----------------------

nodeGroups:

# A node-group locked to a specific Availability Zone, considered
# a 'core' node. Applications that are not zone-agnostics (ie. that need
# EBS-like/gp2 volumes) should use these nodes.
# This allows application deployed here to use EBS (gp2) volumes
# without fear of new instances appearing in other zones.
# Alternatives are EFS if you want to use zone-agnostic nodes.
#
# Applications that don't need core (i.e. have no volume needs) can also use
# this node group but these applications are strongly encouraged
# to use 'application' nodes.
- name: ng-core
  instanceType: t3a.2xlarge
  availabilityZones:
  - eu-central-1a
  minSize: 1
  maxSize: 4
  desiredCapacity: 1
  volumeSize: 80
  volumeType: gp2
  labels:
    informaticsmatters.com/purpose: core

# A node-group for general purpose 'applications'
# that do not need to be on a 'core' node (i.e. are zone-agnostic).
# These nodes are expected to be multi-zoned where gp2 is of little use.
- name: ng-app
  instanceType: t3a.2xlarge
  minSize: 1
  maxSize: 4
  desiredCapacity: 1
  volumeSize: 80
  volumeType: gp2
  labels:
    informaticsmatters.com/purpose: application

# A node-group for worker (transient) applications that do not need to be on a
# 'core' or 'application' node.
- name: ng-worker
  instanceType: t3a.2xlarge
  minSize: 0
  maxSize: 4
  desiredCapacity: 0
  volumeSize: 80
  volumeType: gp2
  labels:
    informaticsmatters.com/purpose: worker
  iam:
    withAddonPolicies:
      autoScaler: true

# Multi-Zone (MZ) application (spot) instances.
# Generally for workflow execution where
# a volume does not have to exist in the designated zone,
# i.e. where EFS volumes are sufficient.
#
# See https://eksctl.io/usage/spot-instances/
# Application instances
#   Type         Size   Spot      Demand
#   ------------ ------ --------- -------
# - t2.xlarge    4/16   $0.0643   $0.2144
# - t3.xlarge    4/16   $0.0621
# - m5.xlarge    4/16   $0.0769
- name: ng-app-spot-mz
  labels:
    purpose: application-mz
  tags:
    k8s.io/cluster-autoscaler/node-template/label/purpose: application-mz
  instancesDistribution:
    maxPrice: 0.080
    instanceTypes:
    - t2.xlarge
    - t3.xlarge
    - m5.xlarge
    onDemandBaseCapacity: 0
    onDemandPercentageAboveBaseCapacity: 0
    spotInstancePools: 3
  desiredCapacity: 1
  minSize: 1
  maxSize: 4
  volumeSize: 80
  privateNetworking: true
  iam:
    withAddonPolicies:
      autoScaler: true
  ssh:
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0bZqMTVETU8t3nzZ60aexkpkeYCt68/ODg7APP6/zUwGxKK9YFk7wUCJwX6xoy6d5NWoa+9IfQ8/YepBUzUy2ypce5V7f2Jx+ugOi3TF9hMFnt+hcUFabazDvsQf+DYr/c+mjXnQl3X6N427WP1x7P9fKnUVjBZxn/LcRDOxzl/TUvR/ncfBvYAPC8q9rtkkTEcx6pj05f39GG/Eek2ayzY0FlqEGuiOlvovMSdRTvVp8CvRSEVi/ArO+wyXcWT9UtfX2JjpRKBHQLZV1oGqCyj86zWYckSNcK3CkMshUIjNoDqlK/9QCjlkjfMzpXakN8b29tA4E8wjsR5hEQb1h

# BigMem nodes (Graph Nodes) need read-access to AWS S3
# as they're expected to download data from the bucket
# that contains the input data for the graph database
# that the node is expected to run.
#
# BigMem (Graph) instances
#   Type         Size
#   ------------ ------
# - r5.2xlarge   8/64
# - r5.4xlarge   16/128
# - r5.8xlarge   32/256
# - r5.12xlarge  48/384
- name: ng-bigmem-1a
  instanceType: r5.4xlarge
  availabilityZones:
  - eu-central-1a
  minSize: 0
  maxSize: 1
  desiredCapacity: 0
  volumeSize: 80
  volumeType: gp2
  privateNetworking: true
  labels:
    purpose: bigmem
  taints:
    purpose: bigmem:NoSchedule
  iam:
    attachPolicyARNs:
    # We need S3 read-access. If we use 'attachPolicyARNs'
    # we must also include the default policies
    # (see https://eksctl.io/usage/iam-policies/).
    - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

# -------------------
# Managed node groups
# -------------------
# Managed node groups provision optimized groups of nodes and EKS will keep
# the nodes up to date with the latest Kubernetes and host OS versions.
