---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: im-main
  region: eu-central-1

# cluster AZs must be set explicitly for single AZ nodegroup example to work
# See https://github.com/weaveworks/eksctl/blob/master/examples/05-advanced-nodegroups.yaml
availabilityZones:
- eu-central-1a
- eu-central-1b
- eu-central-1c

# By design, node groups are immutable.
#            -------------------------
# This means that if you need to change something (other than scaling)
# like the AMI or the instance type of a node group, you would need to
# create a new nodegroup with the desired changes, move the load and
# delete the old one.
#
# Once created and in use - they cannot be changed.

# ----------------------
# Un-managed Node Groups
# ----------------------

nodeGroups:

# A node-group locked to a specific Availability Zone.
# This allows application deployed here to use EBS (gp2) volumes
# without fear of new instances appearing in other zones.
# Alternatives are EFS if you want to use zone-agnostic nodes.
- name: ng-app-1a
  instanceType: t3a.2xlarge
  availabilityZones:
  - eu-central-1a
  minSize: 1
  maxSize: 4
  desiredCapacity: 1
  volumeSize: 80
  volumeType: gp2
  labels:
    purpose: application
  iam:
    withAddonPolicies:
      autoScaler: true
  ssh:
    publicKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0bZqMTVETU8t3nzZ60aexkpkeYCt68/ODg7APP6/zUwGxKK9YFk7wUCJwX6xoy6d5NWoa+9IfQ8/YepBUzUy2ypce5V7f2Jx+ugOi3TF9hMFnt+hcUFabazDvsQf+DYr/c+mjXnQl3X6N427WP1x7P9fKnUVjBZxn/LcRDOxzl/TUvR/ncfBvYAPC8q9rtkkTEcx6pj05f39GG/Eek2ayzY0FlqEGuiOlvovMSdRTvVp8CvRSEVi/ArO+wyXcWT9UtfX2JjpRKBHQLZV1oGqCyj86zWYckSNcK3CkMshUIjNoDqlK/9QCjlkjfMzpXakN8b29tA4E8wjsR5hEQb1h

# BigMem nodes (Graph Nodes) need read-access to AWS S3
# as they're expected to download data from the bucket
# that contains the input data for the graph database
# that the node is expected to run.
#
# BigMem (Graph) instances
#   Type         Size
#   ------------ ------
# - r5.2xlarge   8/64
# - r5.4xlarge   16/128
# - r5.8xlarge   32/256
# - r5.12xlarge  48/384
- name: ng-bigmem-1a
  instanceType: r5.4xlarge
  availabilityZones:
  - eu-central-1a
  minSize: 1
  maxSize: 1
  desiredCapacity: 1
  volumeSize: 80
  volumeType: gp2
  privateNetworking: true
  labels:
    purpose: bigmem
  taints:
    purpose: bigmem:NoSchedule
  iam:
    attachPolicyARNs:
    # We need S3 read-access. If we use 'attachPolicyARNs'
    # we must also include the default policies
    # (see https://eksctl.io/usage/iam-policies/).
    - arn:aws:iam::aws:policy/AmazonS3ReadOnlyAccess
    - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
    - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy

# -------------------
# Managed node groups
# -------------------
# Managed node groups provision optimized groups of nodes and EKS will keep
# the nodes up to date with the latest Kubernetes and host OS versions.
