---

- name: Check cloud config
  ansible.builtin.assert:
    that:
    - cinder_cloud_config|string|length > 0
    - cinder_cloud_config|string != 'SetMe'

- name: Debug
  ansible.builtin.debug:
    msg: Hello

- name: Create cinder plugin object (templates)
  kubernetes.core.k8s:
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - csi-secret-cinderplugin

- name: Create other cinder objects (files)
  kubernetes.core.k8s:
    definition: "{{ lookup('file', '{{ item }}.yaml') }}"
  loop:
  - csi-cinder-driver
  - cinder-csi-controllerplugin-rbac
  - cinder-csi-controllerplugin
  - cinder-csi-nodeplugin-rbac
  - cinder-csi-nodeplugin

- name: Create StorageClasses
  kubernetes.core.k8s:
    definition: "{{ lookup('template', 'storageclass.yaml.j2') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
