---

# Deleting the namespace deletes a lot of stuff for us...

- name: Deleting namespace '{{ cinder_namespace }}'
  k8s:
    state: absent
    definition: "{{ lookup('template', 'namespace.yaml.j2') }}"
    wait: yes

# Now we just have to delete non-namespace cinder objects.

- name: Delete Cinder objects
  k8s:
    state: absent
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - csidriver
  - storageclass
  - rbac-nodeplugin
  - rbac-controllerplugin
