---

- name: Create cinder objects (files)
  kubernetes.core.k8s:
    definition: "{{ lookup('file', '{{ item }}.yaml') }}"
    wait: yes
    wait_timeout: "{{ wait_timeout }}"
  loop:
  - im-rolebinding-sa-psp
  - csi-cinder-driver
  - cinder-csi-controllerplugin-rbac
  - cinder-csi-controllerplugin
  - cinder-csi-nodeplugin-rbac
  - cinder-csi-nodeplugin

- name: Delete Cinder objects (templates)
  kubernetes.core.k8s:
    state: absent
    definition: "{{ lookup('template', '{{ item }}.yaml.j2') }}"
    wait: yes
  loop:
  - csi-secret-cinderplugin
  - im-role-psp
  - storageclass
