---

# Binds the 'open' PSP
# to the StatefulSet (controllerplugin) service account.

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cinder-controllerplugin-psp
  namespace: kube-system
roleRef:
  kind: Role
  name: csi-cinder-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: csi-cinder-controller-sa
  namespace: kube-system

---

# Binds the 'open' PSP
# to the DaemonSet (nodeplugin) service account.

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-cinder-nodeplugin-psp
  namespace: kube-system
roleRef:
  kind: Role
  name: csi-cinder-psp
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: csi-cinder-node-sa
  namespace: kube-system
