---

# Deploy (or un-deploy)?
# One of 'present' or 'absent'.
# If we un-deploy the entire infrastructure deployment is removed -
# the namespace, database, PSPs etc.
infra_state: present

# Database (postgres) ---------------------------------------------------------

# There is no 'state' variable here.
# The database is _always_ deployed.

# The database volume size (Gi).
pg_vol_size_g: 10
# The StorageClass of the postgres persistent volume.
# An blank class implied the cluster default.
pg_storageclass: " "

# Database (backups) ----------------------------------------------------------

# Deploy backup strategy?
# One of 'present' or 'absent'
pg_bu_state: absent
# The database backup volume size (Gi).
pg_bu_vol_size_g: 25
# The backup volume StorageClass.
# This must accommodate the ReadWriteMany access mode.
# An blank class implied the cluster default.
pg_bu_storageclass: " "

# Keycloak --------------------------------------------------------------------

# Deploy (or un-deploy)?
# One of 'present' or 'absent'.
#
# During the infrastructure deployment stage keycloak database credentials
# and a database will be setup in the infrastructure database regardless -
# the Keycloak DB is (at the moment) part of the core database installation.
kc_state: present

# The hostname of the server that will host Keycloak,
# devoid of the protocol (i.e. 'https://' assumed so just 'example.com')
kc_hostname: SetMe
# Kubernetes certificate issuer.
# One of 'staging' or 'production' (rate-limited)
kc_cert_issuer: production

# The password to assign to the admin user of our Keycloak server.
kc_admin: admin
kc_admin_password: "{{ lookup('password', '/dev/null length=12 chars=ascii_letters') }}"

# AWX -------------------------------------------------------------------------

# Deploy (or un-deploy)?
# One of 'present' or 'absent'.
#
# During the infrastructure deployment stage AWX database credentials
# and a database will be setup in the infrastructure database regardless -
# the AWX DB is (at the moment) part of the core database installation.
ax_state: present
# The AWX kubernetes context
# This is typically the control-plane content name
ax_kubernetes_context: minikube

# The hostname of the server that will host AWX,
# devoid of the protocol (i.e. 'https://' assumed so just 'example.com')
ax_hostname: SetMe
# Kubernetes certificate issuer.
# One of 'staging' or 'production' (rate-limited)
ax_cert_issuer: production

# The password to assign to the admin user of our AWX server.
ax_admin: admin
ax_admin_password: "{{ lookup('password', '/dev/null length=14 chars=ascii_letters,digits') }}"
