---

ansible_connection: local
ansible_python_interpreter: python

# Install core?
core_state: present
# Install infrastructure (apps)?
infra_state: present

# The namespace of the deployment,
# our 'infrastructure'. We anticipate
# deploying postgres, the AWX server and Keycloak here.
infra_namespace: im-infra
infra_namespace_service_account: im-infra

# A pull-secret for public images pulled from DockerHub.
# If set this is the base-64 string that can be used as the value
# in our Kubernetes Secret as the .dockerconfigjson value.
# If set it is applied to the ServiceAccount in the namespace
# and applied to Pods that use that namespace.
infra_dockerhub_pullsecret: ''

# Providing your own Kubernetes image pull secrets.
#
# If you have moved the public (docker.io and quay.io) images to
# your own private binary repository like JFrog Artifactory
# you probably need to provide a pull secret for all the images.
# One pull secret must valid for all images.
#
#   - Create the application namespaces in advance of the playbooks
#   - Create the pull secret in each namespace
#   - Provide the name of the secret in the following variable
#     (which will be used for all images)
#
# You must use all public images or you must use all private images.
# You cannot put some images into a private repo and rely on
# public images for the rest - it's "all or none".
all_image_preset_pullsecret_name: ''

# USe PodSecurityPolicy (PSP)?
# Not supported on k8s 1.25
k8s_use_psp: yes

# A named kubeconfig file?
# If set, use this kubernetes config, rather than K8S credentials.
# You would set this if executing the playbooks locally, i.e. not from
# and AWX server, where K8S_AUTH_HOST, K8S_AUTH_API_KEY environment
# variables are set and used.
k8s_kubeconfig: ''
