---

# The EFS provisioner container image tag and its registry.
# One from quay.io/external_storage/efs-provisioner
efs_provisioner_tag: v2.4.0
efs_provisioner_registry: quay.io

# A symbolic name for the provisioner deployment,
# used to direct the storage-class to the provisioner Pod.
efs_provisioner_name: informaticsmatters.com/efs
# The name used for the storage class that will be created.
efs_storage_class_name: efs

# General timeout, generally used within the k8s module,
# for wait duration
wait_timeout: 600

# Provisioner Pod Requests/Limits
efs_cpu_limit: 200m
efs_mem_limit: 128Mi
efs_cpu_request: 100m
efs_mem_request: 128Mi
